# Generated by Django 4.2 on 2026-10-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='khmer_name',
            field=models.CharField(blank=True, default='', help_text='ឈ្មោះជាភាសាខ្មែរ (e.g. ពេជ្រ វល័ក្ខ)', max_length=150, verbose_name='Khmer Name'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['khmer_name'], name='students_st_khmer_n_8ce21e_idx'),
        ),
    ]
